### ISSUE TITLE
Dash 现在的地位还是那么高吗？ 我用的时候感觉不太会用

### ISSUE THREAD

**Issue by Qoiuy** [NsLib/NsLib.github.io#1]
找不到那个感觉。好多时候直接去翻源码了 。
而且我现在用dash 更多是snippets.
感觉好多项目都 找不到文档。

**Comment by NsLib** [comment]
我个人是从 Dash 作者改了收费模式以后就不用了。
文档替代：https://devdocs.io/
snippets：https://www.trankynam.com/atext/

**Comment by Qoiuy** [comment]
嘿嘿嘿 好的 谢谢亮哥
